### ISSUE TITLE
Lista de pessoas que desejam contribuir 

### ISSUE THREAD

**Issue by DanielHe4rt** [he4rt/react4noobs#1]
Deixe seu alô caso você queira contribuir no React4Noobs aqui neste post <3

**Comment by juligaioso** [comment]
alow

**Comment by DevMaktubi** [comment]
aloalo

**Comment by EduSantosBrito** [comment]
alo alo

**Comment by AnnaCampelo** [comment]
Pessoal tem todas as instruções no readme principal do projeto, inclusive link pro trello, caso tenham alguma dúvida podem me procurar pelo Discord :3


Anne#8477

**Comment by mirio0** [comment]
Alô

**Comment by rmsilva1973** [comment]
Alô

**Comment by RicardoMorato** [comment]
AloAloAlo

**Comment by Ronkiro** [comment]
Alô!! :D
