### ISSUE TITLE
Estlização - Tailwind

### ISSUE THREAD

**Issue by MatheusFilg** [he4rt/react4noobs#107]
Criando essa issue para adicionar ao board do projeto. Irei abordar sobre Tailwind e os seguintes pontos:

- Base de como utilizar o Tailwind;
- Pros e Contra;
- Extensões que auxiliam o Tailwind;

Sintam-se livre, para apontar algum tópico que não citei aqui e que considerem importantes, posso ter esquecido algo 😅

**Comment by Rychillie** [comment]
Pode me adicionar a está, tenho muito que contribuir sobre

**Comment by Bluniz** [comment]
@Rychillie Adicionado!
