### ISSUE TITLE
Seção de patterns

### ISSUE THREAD

**Issue by gabrielduete** [he4rt/react4noobs#112]
Seria uma boa ter uma seção de patterns? 

Estava pensando em trazer algum conteúdo como Compound Components, HOC, ou algo do tipo... 

Acho que seria massa abordar esses assuntos de padrões react e tals. Não vejo muitos conteúdos sobre esse tema em português.

**Comment by Bluniz** [comment]
Com certeza seria! HOC principalmente! Acho extremamente válido manito!

**Comment by gabrielduete** [comment]
Trabalhando em: https://github.com/he4rt/react4noobs/pull/116

**Comment by gabrielduete** [comment]
Adicionando seção nas docs: https://github.com/he4rt/react4noobs/pull/121

**Comment by gabrielduete** [comment]
Começamos a trabalhar em React Design Patterns: https://github.com/he4rt/react4noobs/tree/master/docs/Design%20Patterns
