### ISSUE TITLE
Estilização - Styled Components

### ISSUE THREAD

**Issue by Bluniz** [he4rt/react4noobs#128]
Artigo sobre Styled Components

**Comment by gabrielduete** [comment]
Pode me assinar nessa?

**Comment by Bluniz** [comment]
Com certeza! Feito!

**Comment by gabrielduete** [comment]
Mano, pelo que vi já tem uma seção de styled-components, acho que vou pegar outro tema pra fazer

https://github.com/he4rt/react4noobs/blob/master/docs/Estilizacao/3.1-styled-components.md

**Comment by Bluniz** [comment]
Com certeza posso! Ahn, perfeito!
