### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by MatheusFC2** [he4rt/react4noobs#136]
Tive uma ideia de add [Storybook](https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/) dentro da categoria [Bibliotecas de utilidade](https://github.com/he4rt/react4noobs/tree/master/docs/Bibliotecas%20de%20utilidade)

O que vocês acham?

**Comment by gabrielduete** [comment]
Salve, @MatheusFC2! Tranquilo?

Muito bom, mano! Acho uma boa demais, até pro pessoal conhecer mais sobre o Storybook também, da até pra colocar um tópico inicial explicando como funciona.

Quer mandar bala nisso ai?

**Comment by MatheusFC2** [comment]
Salve @gabrielduete, Tranquilo!
Claro, pode deixar!

**Comment by gabrielduete** [comment]
Toop, mano!

Criei a task e te deixei como onwer: https://github.com/he4rt/react4noobs/projects/2#card-92912888

Pode me marcar na PR quando abrir?

Qualquer coisa, só chamar! =)

**Comment by MatheusFC2** [comment]
Marcado mano!

Se tiver mais alguma ideia de campo para adicionar acho melhor discutir aqui ou no PR?

**Comment by gabrielduete** [comment]
Boa, mano!

Já estou olhando a PR. Podemos usar lá mesmo =)
