### ISSUE TITLE
Adicionar na roadmap conteúdo sobre Strict Mode

### ISSUE THREAD

**Issue by Ronkiro** [he4rt/react4noobs#14]
https://reactjs.org/docs/strict-mode.html

autodescritivo

**Comment by DanielHe4rt** [comment]
Qual é o grau de importância disso pra um iniciante? Queria entender um pouco sobre o conteúdo antes de solicitar uma alteração.

**Comment by Ronkiro** [comment]
Na última vez que utilizei, o CRA adicionou o Strict Mode automaticamente. Eu pensei em adicionarmos ao roadmap exatamente por isso. Eu, por exemplo, ainda não conhecia o Strict Mode (Mesmo tendo usado React durante um tempinho).

**Comment by Bluniz** [comment]
Acho extremamente válido explicar sobre, mas acredito que inicialmente precisamos fechar o escopo principal do projeto!
Vou criar uma issue nos projects, e em breve iremos adicionar! Ou se tu quiser também iniciar!

**Comment by Bluniz** [comment]
Adicionado ao nosso [Board](https://github.com/he4rt/react4noobs/projects/2)! Quando for iniciar é possivel mover no board e criar uma issue a partir dela também!
