### ISSUE TITLE
Adicionar seção sobre o create-react-app

### ISSUE THREAD

**Issue by JVictorV** [he4rt/react4noobs#15]
O CRA provavelmente e o primeiro contato de muita gente com o react e tem algumas diferencas pequenas que sao legais de explicar tambem

**Comment by AnnaCampelo** [comment]
Vai rolar uma explicaçãozinha sobre na sessão do npm, não sei também se seria bom separar, é de se conversar.

**Comment by Ronkiro** [comment]
Eu não vejo necessidade de uma seção completamente separada, visto que o CRA é algo consideravelmente simples de se entender.

Mas concordo que o mesmo deve ter uma visibilidade dentro do [README.md da docs](https://github.com/he4rt/react4noobs/blob/master/docs/README.md). Eu apoio que seja criada uma subseção (1.1, por exemplo) com a URL direcionando ao conteúdo do CRA por dentro da seção do `npm`. Não sei se deu para entender haha
