### ISSUE TITLE
Implementar seção Typescript

### ISSUE THREAD

**Issue by Carolis** [he4rt/react4noobs#22]

**Comment by Ronkiro** [comment]
@Rhedrum Alguém já pegou essa? Como pupilo do Angular, tenho total interesse de montar essa c:

**Comment by Ronkiro** [comment]
Ignora, vi agora que cê tá pegando ali no Discord :smile:

**Comment by Rhedrum** [comment]
> Ignora, vi agora que cê tá pegando ali no Discord 😄

@Ronkiro  Fica a vontade pra ajudar também pô hahaha
E sobre os tópicos faltantes fui aconselhada a olhar no  board de "projects" mesmo, acredito que a Anne está atualizando os status lá =)

**Comment by Ronkiro** [comment]
De boa kkkkkkk Qualquer coisa eu aproveito quando tiver finalizado p/ ver se não incremento, aí garantimos que tá completinho. Eu tinha mandado mensagem antes de ler ;-;

**Comment by Rhedrum** [comment]
@Ronkiro Tranquilo, melhor ainda. Vou te atualizando/alinhando contigo sobre os tópicos

**Comment by guieiras** [comment]
@AnnaCampelo podemos fechar essa issue? O PR já está mergeado
