### ISSUE TITLE
Link quebrado no arquivo sobre Componetização

### ISSUE THREAD

**Issue by jadsonluan** [he4rt/react4noobs#37]
Olá! :smiley: 

O link **Dividindo interface em componentes**, no arquivo sobre [Componetização](https://github.com/he4rt/react4noobs/blob/master/docs/Iniciando%20com%20React/3-Componentizacao.md), está com algum problema. Quando eu o acesso, ele leva para uma página que exibe apenas a mensagem `Invalid upstream response (403)`

**Comment by Ronkiro** [comment]
Acho que pode ser fechado

**Comment by jadsonluan** [comment]
Acredito que sim, @Ronkiro . Vou fechar!
