### ISSUE TITLE
Implementar Seção CSS in JS

### ISSUE THREAD

**Issue by rafasilveira** [he4rt/react4noobs#49]
Salve!

Me disponibilizo a cobrir [esse card](https://github.com/he4rt/react4noobs/projects/1#card-43303805) 😄

**Comment by joaobispo2077** [comment]
Opa beleza @rafasilveira ! também estou completamente interessado na criação dessa seção, se quiser um help qualquer coisa é só chamar! Vou tentar dar subscribe assim que você criar para que eu acompanhe (que repositório maravilhoso é esse react4noobs!)

**Comment by rafasilveira** [comment]
Opa! PR criada https://github.com/he4rt/react4noobs/pull/52
