### ISSUE TITLE
Implementar seção Next.Js

### ISSUE THREAD

**Issue by joaobispo2077** [he4rt/react4noobs#50]
Olá pessoal!

Eu gostaria de cobrir a seção do card <a href="https://github.com/he4rt/react4noobs/projects/1#card-43303866">Next.Js</a>, ainda estou reunindo ideias lendo como foram feitas outras seções para que eu consiga apresentar tanto recursos como o SSR quanto funcionalidades interessantes de Next.Js + Vercel de forma agradável.

**Comment by guieiras** [comment]
Boa! Precisando de alguma coisa, me disponho a ajudar a elaborar conteúdo ou revisar o texto.

**Comment by AnnaCampelo** [comment]
Show! :3

**Comment by joaobispo2077** [comment]
Fala galera,

Finalmente, conclui o conteúdo desse artigo,  está nesse [PR](https://github.com/he4rt/react4noobs/pull/72).
