### ISSUE TITLE
Implementação sobre Gatsby

### ISSUE THREAD

**Issue by vensauro** [he4rt/react4noobs#58]
Hi galere,

Eu gostaria de contribuir incluindo a seção sobre [Gatsby](https://github.com/he4rt/react4noobs/projects/1#card-43303868) <3

**Comment by DanielHe4rt** [comment]
Você pode colocar no final da documentação os tópicos que você deseja inserir sobre a linguagem. 

Podemos usar essa issue pra discutir o que será inserido e organizar de fato essa nova feature! Eu agradeceria demais um conteúdo sobre Gatsby.
