### ISSUE TITLE
Recomendação sobre React Query

### ISSUE THREAD

**Issue by vensauro** [he4rt/react4noobs#59]
Olá, tava vendo a doc, e vi que em request tem fetch e axios, eu gostaria de recomendar colocar tambem o React Query ou SWR
para fazer essas recomendações tem algum padrão?

**Comment by vensauro** [comment]
Sendo que eu posso me responsabilizar a fazer essa seção se for aceita

**Comment by AnnaCampelo** [comment]
Certo, se você acha que válido para um iniciante seria ótimo! Porém, acredito que antes seria importante concluir todas as nossas tasks pendentes no nosso [github projects](https://github.com/he4rt/react4noobs/projects/1)

**Comment by RodrigoRVSN** [comment]
Concordo que ferramentas de gerenciamento de estado do servidor (Server State Management) estão tomando cada vez mais lugar para controle assíncrono
