### ISSUE TITLE
Dividir o tópico sobre hooks em diversos subtópicos

### ISSUE THREAD

**Issue by BRonen** [he4rt/react4noobs#97]
Mantendo a descrição de todos os hooks em um arquivo só limita a capacidade de acrescentar conteúdo sem prejudicar a usabilidade por não ser tão bem indexado quanto dividir entre diversos arquivos com conteúdos sobre cada hook.

**Comment by MatheusFC2** [comment]
Verdade facilitaria usabilidade, podemos também criar um subtópico para Hooks personalizados.
